###查询评论体信息接口
POST http://127.0.0.1:33001/api/comtBody/getComtBody
Content-Type: application/json

{
    "cbId":2
}

###创建评论体接口
POST http://127.0.0.1:33001/api/comtBody/createComtBody
Content-Type: application/json

{
    "cbId":9,
    "cbImg":"http://22225.com",
    "cbText":"广东医123",
    "cbTitle":"广东医213",
    "userId":1
}

###修改评论体接口
POST http://127.0.0.1:33001/api/comtBody/modifyComtBody
Content-Type: application/json

{
    "cbId":2,
    "cbImg":"http://2222.com",
    "cbText":"广东医666",
    "cbTitle":"广东医888 ",
    "userId":1
}
###删除评论体接口
POST http://127.0.0.1:33001/api/comtBody/deleteComtBody
Content-Type: application/json

{
    "cbId": 1
}