###查询提问接口
POST http://127.0.0.1:33001/api/question/getQuestion
Content-Type: application/json

{
    "cbId":1,
    "questionId":1
}

###创建新提问接口
POST http://127.0.0.1:33001/api/question/createQuestion
Content-Type: application/json

{
    "cbId":1,
    "userId":1,
    "questionId":2,
    "text":"广东医有什么好吃的？"
}