###登录
POST http://127.0.0.1:33001/api/user/getUser
Content-Type: application/json

{
    "account":"text_02",
    "password":"123456"
}



###查询用户信息接口
POST http://127.0.0.1:33001/api/user/getUserInfor
Content-Type: application/json


###创建新用户接口
POST http://127.0.0.1:33001/api/user/createUser
Content-Type: application/json

{
    "userId":"0190c9e4-684a-7070-a326-d0b5c07d65b1",
    "account":"text_02",
    "password":"123456"
}
